// Code generated by qtc from "error.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../../internal/server/views/error.qtpl:1
package views

//line ../../internal/server/views/error.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../internal/server/views/error.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../internal/server/views/error.qtpl:1
func StreamErrorPage(qw422016 *qt422016.Writer, err string) {
//line ../../internal/server/views/error.qtpl:1
	qw422016.N().S(`
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
</head>
<body>
    <h1>Error</h1>
    `)
//line ../../internal/server/views/error.qtpl:9
	qw422016.E().S(err)
//line ../../internal/server/views/error.qtpl:9
	qw422016.N().S(`
</body>
</html>
`)
//line ../../internal/server/views/error.qtpl:12
}

//line ../../internal/server/views/error.qtpl:12
func WriteErrorPage(qq422016 qtio422016.Writer, err string) {
//line ../../internal/server/views/error.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../internal/server/views/error.qtpl:12
	StreamErrorPage(qw422016, err)
//line ../../internal/server/views/error.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line ../../internal/server/views/error.qtpl:12
}

//line ../../internal/server/views/error.qtpl:12
func ErrorPage(err string) string {
//line ../../internal/server/views/error.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../internal/server/views/error.qtpl:12
	WriteErrorPage(qb422016, err)
//line ../../internal/server/views/error.qtpl:12
	qs422016 := string(qb422016.B)
//line ../../internal/server/views/error.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../internal/server/views/error.qtpl:12
	return qs422016
//line ../../internal/server/views/error.qtpl:12
}
