// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../../internal/server/views/index.qtpl:1
package views

//line ../../internal/server/views/index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../internal/server/views/index.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../internal/server/views/index.qtpl:1
func StreamIndexPage(qw422016 *qt422016.Writer, connectionString string, result string) {
//line ../../internal/server/views/index.qtpl:1
	qw422016.N().S(`
<html lang="en">
    <body>
        <h1>Connection test</h1>
        <form action="connection_test" method="post">
            <label>
                Connection string
                <input type="text" name="connection_string" value="`)
//line ../../internal/server/views/index.qtpl:8
	qw422016.E().S(connectionString)
//line ../../internal/server/views/index.qtpl:8
	qw422016.N().S(`" size="80">
            </label>
            <input type="submit">
        </form>

        `)
//line ../../internal/server/views/index.qtpl:13
	if result != "" {
//line ../../internal/server/views/index.qtpl:13
		qw422016.N().S(`
            <h1>Status: `)
//line ../../internal/server/views/index.qtpl:14
		qw422016.E().S(result)
//line ../../internal/server/views/index.qtpl:14
		qw422016.N().S(`</h1>
        `)
//line ../../internal/server/views/index.qtpl:15
	}
//line ../../internal/server/views/index.qtpl:15
	qw422016.N().S(`
    </body>
</html>
`)
//line ../../internal/server/views/index.qtpl:18
}

//line ../../internal/server/views/index.qtpl:18
func WriteIndexPage(qq422016 qtio422016.Writer, connectionString string, result string) {
//line ../../internal/server/views/index.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../internal/server/views/index.qtpl:18
	StreamIndexPage(qw422016, connectionString, result)
//line ../../internal/server/views/index.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line ../../internal/server/views/index.qtpl:18
}

//line ../../internal/server/views/index.qtpl:18
func IndexPage(connectionString string, result string) string {
//line ../../internal/server/views/index.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../internal/server/views/index.qtpl:18
	WriteIndexPage(qb422016, connectionString, result)
//line ../../internal/server/views/index.qtpl:18
	qs422016 := string(qb422016.B)
//line ../../internal/server/views/index.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../internal/server/views/index.qtpl:18
	return qs422016
//line ../../internal/server/views/index.qtpl:18
}
